### ISSUE TITLE
Create demo

### ISSUE THREAD

**Issue by HannaLindgren** [stts-se/segment_checker#8]
- [x] #1 Design protocol for source data
- [x] #2 Send source data protocol to customer
- [x] #3 Create layout based on provided draft
- [x] #4 Create simplified GUI
- [x] #5 Create protocol for annotation data
- [x] #6 File/folder hierarchy
- [x] #7 Create server with Rest API
- [x] Testing
